version: "3"
services:
  react-docker-image:
    container_name: react-docker-image
    image: react-docker-image
    restart: always
    build: .
    ports:
      - "4001:3001"
    environment:
      PORT: "3001"
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true